#!/bin/sh

# Autostart apps
~/.config/bspwm/autostart.sh

wmname LG3D

# Workspace config
bspc monitor -d 1 2 3 4 5 7 8 9 10
bspc config focus_follows_pointer true
bspc config normal_border_color		"#3c444d"
bspc config active_border_color		"#ffffff"
bspc config focused_border_color	"#ffffff"
bspc config presel_feedback_color	"#ffffff"

# Border & gaps
bspc config border_width 2 
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config window_gap 10
bspc config split_ratio 0.50

# App rules
bspc rule -a nitrogen state=floating focus=on
bspc rule -a Emacs state=tiled
bspc rule -a java state=tiled

